const colors = {
  PRIMARY_COLOR: "#5C65C0",
  PRIMARY_DARK: "#301C41",
  PRIMARY_LIGHT: "#7166BA",

  SECONDARY_COLOR: "#6F95FF",
  SECONDARY_DARK: "#1A45BE",
  SECONDARY_LIGHT: "#9AB5FF",

  TITLE_COLOR: "##EFEFEF",
  TEXT_COLOR: "#EFEFEF",

  BACKGROUND: "#1C0B2B",
  BACKGROUND_2: "#301C41",
};

export { colors };
